--1. Write a SQL Query to create a table Passenger.
         CREATE TABLE PASSENGER (PASSENGERID NUMBER PRIMARY KEY, 
FIRST VARCHAR(20) NOT NULL, 
MIDDLE VARCHAR(20) NOT NULL, 
LAST VARCHAR(20) NOT NULL, 
GENDER CHAR(1) NOT NULL,
PHONE NUMBER NOT NULL,
EMAIL VARCHAR(50) NOT NULL, 
PASSENGERTYPE VARCHAR(20));

--2. Write a SQL Query to Create a table Agency_Discount.
CREATE  TABLE AGENCY DISCOUNT (AGENCYDISCOUNTCODE NUMBER PRIMARY KEY,    AGENCYDISCOUNTAMOUNT NUMBER (8,2) NOT NULL);

--3. Write a SQL Query to create a table Travel_agency.

CREATE TABLE TRAVEL_ AGENCY (TPASSENGERID NUMBER PRIMARY KEY,
TRAVELAGENCYID NUMBER NOT NULL,
TRAVELAGENCYNAME VARCHAR(50) NOT NULL,
 AGENCYADDRESS VARCHAR(50) NOT NULL,
 AGENCYPHONE NUMBER NOT NULL,
 BOOKINGAGENTNAME VARCHAR(50) NOT NULL,
             AGENCYDISCOUNTCODE NUMBER NOT NULL, FOREIGN KEY      
             (AGENCYDISCOUNTCODE) REFERENCES AGENCY_DISCOUNT           
             (AGENCYDISCOUNTCODE));

--4. Write a SQL Query to create a table Travel_class.

CREATE TABLE TRAVEL_CLASS(TRAVELCLASSID NUMBER PRIMARY KEY,
TRAVELCLASS CHAR(20) NOT NULL);

--5. Write a SQL Query to create a table Reservation_status.
CREATE TABLE RESERVATION_STATUS
(RESERVATIONSTATUSID NUMBER PRIMARY KEY,
 RESERVATIONSTATUS VARCHAR(20) NOT NULL);

--6. Write a SQL Query to create a table Airline.
CREATE TABLE AIRLINE(AIRLINECODE CHAR(10) PRIMARY KEY,
AIRLINENAME VARCHAR(50) NOT NULL,
HEADQUARTERSADDRESS VARCHAR(50) NOT NULL)

--7. Write a SQL Query to Create a table Flight.

	CREATE TABLE FLIGHT (FLIGHTNUMBER CHAR(10) PRIMARY KEY,
 	DESTINATION VARCHAR(50) NOT NULL,
 	FLIGHTDATE DATE NOT NULL,
 	DEPARTURETIME TIMESTAMP(0) NOT NULL,
 	ARRIVALTIME TIMESTAMP(0) NOT NULL,
 	FLIGHTTIME TIMESTAMP(0) NOT NULL,
 	AIRLINECODE CHAR(10), 
 	FOREIGN KEY (AIRLINECODE) REFERENCES  AIRLINE            
            (AIRLINECODE) );

--8. Write a SQL Query to Create a table Reservation.

CREATE TABLE RESERVATION (RESERVATIONID NUMBER PRIMARY KEY,
PASSENGERID NUMBER NOT NULL,
FLIGHTNUMBER CHAR(1) NOT NULL,
RESERVATIONDATE DATE NOT NULL,
SEATNUMBER CHAR(4) NOT NULL,
COST DECIMAL (8,2) NOT NULL,
TRAVELCLASSID NUMBER NOT NULL,
RESERVATIONSTATUSID NUMBER NOT NULL,
FOREIGN KEY (PASSENGERID) 
REFERENCES PASSENGER (PASSENGERID),
FOREIGN KEY (FLIGHTNUMBER) 
REFERENCES FLIGHT (FLIGHTNUMBER),
FOREIGN KEY (TRAVELCLASSID) 
REFERENCES TRAVEL_CLASS(TRAVELCLASSID), 
FOREIGN KEY (RESERVATIONSTATUSID) 
REFERENCES RESERVATION_STATUS (RESERVATIONSTATUSID) );
